### PR TITLE
Fix workaround dense templates incorrectly saved as dense templates

### PR DESCRIPTION
**Pull request by balefebvre**
See this [comment](https://github.com/cortex-lab/phylib/commit/a4a9048e89c9f2de2e4c2078d7ba9fcb760fd015#commitcomment-36046540).

### CODE REVIEW

**Comment by rossant** [comment]
LGTM
@oliche  agreed?

**Comment by yger** [comment]
Any update on this? Can we merge this PR since this is slightly annoying for the sparse export of SC?

**Comment by yger** [comment]
@rossant can it be done, or is there something more complicated with this PR?

**Comment by rossant** [comment]
Please excuse me for the delay, we'll have a look today!

**Comment by yger** [comment]
No hurry but still, this is just breaking the export for us. And of course, there is also this line.... L666 (the line of the devil :-))
out = np.dot(x, mat)   # * 20
Why the * 20 ? We also need to comment this to have a proper scaling

**Comment by rossant** [comment]
OK should be done
and for the scaling it should be back to normal, there is a new optional `template_scaling` parameter in the `params.py` file

**Comment by yger** [comment]
Thanks a lot!

**Pull request merged**
