### PR TITLE
convert amp values to V

### PR DESCRIPTION
**Pull request by jaib1**
Something like this, but maybe could be made better?

### CODE REVIEW

**Comment by jaib1** [comment]
also in `test_merge`, not sure why `test_merged_single(merged)` is passing, but `test_merged_single(alf)` fails. maybe we could go over this test together?

**Comment by oliche** [comment]
2 comments on this:

- I think we will need thorough testing, not only checking that the code executes, but also checking amplitudes values.
- the function doesn't convert to volts but to whatever was in the bin file, almost always sample values. I would add an optional scaling_factor argument (defaults to 1) that we can apply to get real world units, but this is specific to each dataset.

**Comment by jaib1** [comment]
> the function doesn't convert to volts but to whatever was in the bin file, almost always sample values. I would add an optional scaling_factor argument (defaults to 1) that we can apply to get real world units, but this is specific to each dataset.

yes, I thought this was the point of `ampfactor` ?

**Comment by oliche** [comment]
Absolutely, sorry I didn't see it was outside of the method. All good on this point.

**Pull request closed without merging**
